version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: ./app
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    env_file:
      - ./.env
    depends_on:
      - mongo

volumes:
  mongo_data:
